JustWork.Website/Controllers/InviteController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using JustWork.Common;
using JustWork.Logic.DTO;
using JustWork.Logic.Interface;
using JustWork.Model.OrdersViewModels;
using JustWork.Website.Infastructure.Interfaces;

namespace JustWork.Website.Controllers
{
    public class InviteController : Controller
    {
        private readonly IOrderInviteService _inviteService;
        private readonly IAccountService _accountService;
        private readonly IEmailNotifer _emailNotificator;
        private readonly IOrderService _orderService;

        public InviteController(
            IOrderInviteService inviteService,
            IAccountService accountService, 
            IEmailNotifer emailNotificator, 
            IOrderService orderService
            )
        {
            _inviteService = inviteService;
            _accountService = accountService;
            _emailNotificator = emailNotificator;
            _orderService = orderService;
        }

        [HttpPost]
        [Authorize(Roles = "employer")]
        [ValidateInput(false)]
        public async Task<JsonResult> Add(InviteViewModel inviteModel)
        {
            var currentUser = _accountService.GetByUsernameWithInclude(User.Identity.Name);
            var order = _orderService.GetById(inviteModel.OrderId);
            if (order.OrderInvites.Any(orderInv => orderInv.Employer.Id == currentUser.Id))
            {
                return null; 
            }

            var invite = new OrderInviteDTO
            {
                Employer = currentUser,
                Message = inviteModel.Description,
                Cost = inviteModel.Cost,
                Order = new OrderDTO { Id = inviteModel.OrderId }
            };
            await NotifyAboutInvite(inviteModel.OrderId);
            _inviteService.Create(invite);
            return Json(invite);
        }

        private async Task NotifyAboutInvite(int orderId)
        {
            var order = _orderService.GetById(orderId);
            var orderLink = Url.Action("Show", "Order", new {id = orderId}, Request.Url.Scheme);
            if (!order.Customer.UserDto.ConfirmEmail) return;
            var body = ConfigurationsConstants.NewInviteMsg + $"<a href=\"{orderLink}\">Order Link</a>";
            await _emailNotificator.SendNotificationAsync(order.Customer.UserDto.Email, body);
        }

        [HttpGet]
        public ActionResult InviteShow(int id)
        {
            var invite = _inviteService.GetById(id);
            return PartialView("InviteViews/InviteListShow", new List<OrderInviteDTO>{ invite });
        }

        [HttpDelete]
        public ActionResult Delete(int inviteId)
        {
            var invite = _inviteService.GetById(inviteId);
            if (invite.Employer.UserDto.Login != User.Identity.Name)
            {
                return HttpNotFound();
            }
            _inviteService.Delete(invite);
            return new EmptyResult();
        }

        [HttpGet]
        [Authorize]
        public ActionResult LoadlIventForm()
        {
            return PartialView("InviteViews/NewInvite", new InviteViewModel());
        }
    }
}

JustWork.Website/Controllers/OrderController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using AutoMapper;
using JustWork.Common;
using JustWork.Logic.DTO;
using JustWork.Logic.Interface;
using JustWork.Model;
using JustWork.Model.OrdersViewModels;
using JustWork.Website.Infastructure;
using JustWork.Website.Infastructure.Interfaces;
using JustWork.Website.Infastructure.Mappers;

namespace JustWork.Website.Controllers
{
    public class OrderController : Controller
    {
        private readonly IAccountService _accountService;
        private readonly IOrderService _orderService;
        private readonly IOrderSearchService _orderSearchService;
        private readonly IRatingService _ratingService;
        private readonly IEmailNotifer _emailNotificator;

        public OrderController(
            IAccountService accountService,
            IOrderService orderService,
            IOrderSearchService orderSearchService,
            IRatingService ratingService,
            IEmailNotifer emailNotificator
            )
        {
            _accountService = accountService;
            _orderService = orderService;
            _orderSearchService = orderSearchService;
            _ratingService = ratingService;
            _emailNotificator = emailNotificator;
        }

        [HttpGet]
        public ActionResult Show(int id)
        {
            var order = _orderService.GetById(id);
            var viewModel = OrderMapper.MapDtoModelToView(order);
            return View(viewModel);
        }

        [HttpGet]
        [ValidateInput(false)]
        public ActionResult Index(string search, int? page, string criterion, int? maxValue, int? minValue)
        {
            var filter = new FilterViewModel();
            if (maxValue.HasValue && minValue.HasValue)
            {
                filter = new FilterViewModel
                {
                    Criterion = criterion,
                    MaxValue = maxValue.Value,
                    MinValue = minValue.Value
                };
            }
            var orders = _orderSearchService.Search(search, page, new[] { filter }, i => i.OrderStateId == (int)OrderStates.New);
            return View(orders);
        }

        [HttpGet, Authorize]
        public ActionResult Create()
        {
            return View(new OrderViewModel());
        }

        [HttpPost, Authorize]
        [ValidateInput(false)]
        public ActionResult Create(OrderViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var orderCustomer = _accountService.GetByUsernameWithInclude(User.Identity.Name);
            var newOrder = OrderMapper.MapViewToDtoModel(model);

            newOrder.Customer = orderCustomer;
            newOrder.ImageDto = new ImageDTO();
            if (model.ImageFile != null && model.ImageFile.ContentLength > (int)ByteFileSizes.Megabyte * 15)
            {
                ModelState.AddModelError("", @"The file size exceeds the maximum. (15 MB)");
                return View(model);
            }
            if(model.ImageFile != null)
            {
                var fileSplitName = model.ImageFile.FileName.Split('.');
                var fileExtension = (fileSplitName.Length > 1) ? "." + fileSplitName[1] : string.Empty;
                if (!ConfigurationsConstants.ImageFormats.Contains(fileExtension))
                {
                    ModelState.AddModelError("", @"Invalid image format");
                    return View(model);
                }

                var fileName = SaveImageOnServer(model.ImageFile);
                newOrder.ImageDto.ImagePath = "/Images/Uploads/Orders/" + fileName;
            }
            _orderService.Create(newOrder);
            return RedirectToAction("Index");
        }

        [HttpGet]
        [JwAuthorize]
        public ActionResult Edit(int id)
        {
            var order = _orderService.GetById(id);
            if (order.Customer.UserDto.Login != User.Identity.Name)
            {
                return RedirectToAction("AccessDenied", "Error");
            }

            if (order.OrderStateDto.Id != (int)OrderStates.New)
            {
                return RedirectToAction("AccessDenied", "Error");
            }

            var view = OrderMapper.MapDtoModelToView(order);
            return View(view);
        }

        [HttpPost]
        [JwAuthorize]
        [ValidateInput(false)]
        public ActionResult Edit(OrderViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            var updatedOrder = _orderService.GetById(viewModel.Id);

            if (updatedOrder.Customer.UserDto.Login != User.Identity.Name)
            {
                return RedirectToAction("AccessDenied", "Error");
            }

            if (updatedOrder.OrderStateDto.Id != (int)OrderStates.New)
            {
                return RedirectToAction("AccessDenied", "Error");
            }

            Mapper.Map(viewModel, updatedOrder);

            if (viewModel.ImageFile != null && viewModel.ImageFile.ContentLength > (int)ByteFileSizes.Megabyte * 15)
            {
                ModelState.AddModelError("", @"The file size exceeds the maximum. (15 MB)");
                return View(viewModel);
            }

            if (viewModel.ImageFile != null)
            {
                var fileSplitName = viewModel.ImageFile.FileName.Split('.');
                var fileExtension = (fileSplitName.Length > 1) ? "." + fileSplitName[1] : string.Empty;
                if (!ConfigurationsConstants.ImageFormats.Contains(fileExtension))
                {
                    ModelState.AddModelError("", @"Invalid image format");
                    return View(viewModel);
                }

                var fileName = SaveImageOnServer(viewModel.ImageFile);
                updatedOrder.ImageDto = new ImageDTO
                {
                    ImagePath = "/Images/Uploads/Orders/" + fileName
                };
            }

            _orderService.Update(updatedOrder);
            return RedirectToAction("Show", new { id = viewModel.Id });
        }

        [HttpGet]
        [JwAuthorize]
        public ActionResult Delete(int id)
        {
            var order = _orderService.GetById(id);
            if (order.Customer.UserDto.Login != User.Identity.Name)
            {
                return RedirectToAction("AccessDenied", "Error");
            }

            _orderService.Delete(order);
            return RedirectToAction("Index");
        }

        [HttpGet]
        [JwAuthorize]
        public async Task<ActionResult> ChoiceEmployer(int ordedId, int employId)
        {
            var order = _orderService.GetById(ordedId);
            if (order.Customer.UserDto.Login != User.Identity.Name)
            {
                return RedirectToAction("AccessDenied", "Error");
            }

            var newEmploy = _accountService.GetById(employId);
            order.Employer = newEmploy;
            order.OrderStateDto = new OrderStateDTO { Id = (int)OrderStates.InProgress };
            _orderService.Update(order);
            await NotifyAboutInviteChoice(order);
            return RedirectToAction("Show", new { id = ordedId });
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult SearchOrder(string search, FilterViewModel[] filters, int? page)
        {
            var orders = _orderSearchService.Search(search, page, filters);
            return PartialView("OrderPage/OrdersShow", orders);
        }

        [HttpGet]
        public ActionResult FinishOrder(int orderId)
        {
            var order = _orderService.GetById(orderId);
            if (!User.Identity.IsAuthenticated || order.Customer.UserDto.Login != User.Identity.Name)
            {
                return HttpNotFound("Finish order access denied");
            }
            var finishModel = new OrderFinishViewModel { Id = orderId };
            return PartialView("OrderPage/OrderFinishForm", finishModel);
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> FinishOrder(OrderFinishViewModel orderModel)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("InternalServerError", "Error");
            }

            var order = _orderService.GetById(orderModel.Id);
            if (!User.Identity.IsAuthenticated || order.Customer.UserDto.Login != User.Identity.Name)
            {
                return HttpNotFound("Finish order access denied");
            }

            var ratingModel = new RatingDTO
            {
                AccountDto = order.Customer,
                OrderDto = order,
                Message = orderModel.Message,
                RatingValue = orderModel.RatingValue
            };

            if (order.RatingsDto.Any(rate => rate.AccountDto.UserDto.Login == User.Identity.Name))
            {
                return HttpNotFound("\"Add rating\" access denied");
            }

            order.OrderStateDto = new OrderStateDTO { Id = orderModel.OrderStateId };
            _orderService.Update(order);
            _ratingService.Create(ratingModel);
            await NotifyAboutStateChange(order);
            return RedirectToAction("Show", new { id = order.Id });
        }

        [HttpGet]
        public ActionResult AddRating(int orderId)
        {
            var order = _orderService.GetById(orderId);
            var currentUser = User.Identity.Name;
            if (!User.Identity.IsAuthenticated || order.Employer.UserDto.Login != currentUser)
            {
                return HttpNotFound("\"Add rating\" access denied");
            }
            var finishModel = new OrderFinishViewModel { Id = orderId };

JustWork.Website/Views/Shared/InviteViews/InviteListShow.cshtml
@using JustWork.Common
@using JustWork.Logic.DTO
@model ICollection<OrderInviteDTO>
@{
    var currentUserLogin = User.Identity.Name;

    var order = Model.First().Order;

    var orderIsNew = order.OrderStateDto.Id == (int)OrderStates.New;
    OrderInviteDTO choicedInvite = null;
    if (!orderIsNew)
    {
        choicedInvite = Model.First(src => src.Employer.Id == order.Employer.Id);
        Model.Remove(choicedInvite);
    }
}

@if (choicedInvite != null)
{
    <div class="box col-md-10 col-xs-12 invite-content choised">
        @Html.Partial("InviteViews/InviteShow", choicedInvite)
    </div>
}

@foreach (var orderInvite in Model)
{
    var orderCustomerLogin = orderInvite.Order.Customer.UserDto.Login;
    var inviteAuthorLogin = orderInvite.Employer.UserDto.Login;
    <div class="invite-block">
        <div class="box col-md-10 col-xs-12 invite-content">

            <div class="inviteBlock">
                @Html.Partial("InviteViews/InviteShow", orderInvite)
                @if (currentUserLogin == inviteAuthorLogin && orderIsNew)
                {
                    <div class="float-right">
                        <a class="btn btn-common invite-delete invite-button" id="inviteDelete" val="@orderInvite.Id">Delete</a>
                    </div>
                }
                @if (currentUserLogin == orderCustomerLogin && orderIsNew)
                {
                    @Html.ActionLink("Choice", "ChoiceEmployer", "Order", new
               {
                   ordedId = orderInvite.Order.Id,
                   employId = orderInvite.Employer.Id
               }, new {@class = "btn btn-common invite-button invite-choice-btn" })
                }
            </div>
        </div>
    </div>
}

JustWork.Website/Views/Shared/InviteViews/InviteShow.cshtml
@using JustWork.Website.Infastructure
@model JustWork.Logic.DTO.OrderInviteDTO

@{
    var inviteAuthorName = Model.Employer.Name;
    var inviteAuthorLogin = Model.Employer.UserDto.Login;
    var avatarPath = Model.Employer.Avatar.ImagePath;
    var currentUserLogin = User.Identity.Name;
    var orderCustomerLogin = Model.Order.Customer.UserDto.Login;
}

<div class="col-sm-3 col-xs-12">
    <h4 class="invite-athor-link">
        <a href="@Url.Action("ViewProfile", "Account", new {login = inviteAuthorLogin})">@inviteAuthorName</a>
    </h4>
    <a href="@Url.Action("ViewProfile", "Account", new {login = inviteAuthorLogin})">
        <img src="@Html.ImageOrDefaultAvatar(avatarPath)" onerror="onImageErrorHandler(this)" id="avatar" alt="avatar" class="invite-avatar img-thumbnail" />
    </a>
</div>

<div class="col-sm-9 col-xs-12 invite-description">
    @if (currentUserLogin == inviteAuthorLogin || orderCustomerLogin == currentUserLogin)
    {
        <h3 class="invite-cost">Cost: $@Model.Cost</h3><br />
    }
    <h4><b>Message: </b></h4>
    <p class="text-justify rating-message">@Model.Message </p>
</div>

JustWork.Website/Views/Shared/InviteViews/NewInvite.cshtml
@model JustWork.Model.OrdersViewModels.InviteViewModel
<div class="col-md-10 new-invite-form box">
    <div class="my-account-form">
        <h3 class="medium-title">New Invite</h3>
        @using (Html.BeginForm("Add", "Invite", new { inviteModel = Model }, FormMethod.Post, new { id = "newInviteForm" }))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.OrderId)
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <h4>Cost</h4>
                <div class="input-icon">
                    <i class="ti-money"></i>
                    @Html.TextBoxFor(model => model.Cost, new { @class = "form-control", placeholder = "Cost" })
                </div>
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
                <div class="form-group">
                    <h4>Description</h4>
                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control new-invite-area", placeholder = "Description", rows = 4 })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text - danger" })
                </div>
                <div class="form-group submit-form-group">
                    <input type="submit" value="Send" class="btn btn-common invite-button" />
                </div>
        }
    </div>
</div>
@Scripts.Render("~/bundles/jqueryval")